// Code generated by MockGen. DO NOT EDIT.
// Source: goutbox.go
//
// Generated by this command:
//
//	mockgen -source=goutbox.go -destination=mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	goutbox "github.com/IsaacDSC/goutbox"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStore) Create(ctx context.Context, task goutbox.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), ctx, task)
}

// DiscardTask mocks base method.
func (m *MockStore) DiscardTask(ctx context.Context, key string, isOk bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscardTask", ctx, key, isOk)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiscardTask indicates an expected call of DiscardTask.
func (mr *MockStoreMockRecorder) DiscardTask(ctx, key, isOk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscardTask", reflect.TypeOf((*MockStore)(nil).DiscardTask), ctx, key, isOk)
}

// GetTasksWithError mocks base method.
func (m *MockStore) GetTasksWithError(ctx context.Context) ([]goutbox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksWithError", ctx)
	ret0, _ := ret[0].([]goutbox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksWithError indicates an expected call of GetTasksWithError.
func (mr *MockStoreMockRecorder) GetTasksWithError(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksWithError", reflect.TypeOf((*MockStore)(nil).GetTasksWithError), ctx)
}

// UpdateTaskError mocks base method.
func (m *MockStore) UpdateTaskError(ctx context.Context, task goutbox.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskError", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskError indicates an expected call of UpdateTaskError.
func (mr *MockStoreMockRecorder) UpdateTaskError(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskError", reflect.TypeOf((*MockStore)(nil).UpdateTaskError), ctx, task)
}
